name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      CALC_EXPORTS_DIR: ${{ github.workspace }}/exports
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install -r requirements.txt

      - name: Run tests (pytest) and produce junit report
        run: |
          mkdir -p pytest-reports
          pytest -q --maxfail=1 --disable-warnings \
            --junitxml=pytest-reports/junit-${{ matrix.python-version }}.xml

      - name: Upload pytest report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports-${{ matrix.python-version }}
          path: pytest-reports/

      - name: Build wheel and sdist
        run: |
          pip install build
          python -m build

      - name: Upload dist artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.python-version }}
          path: dist/*
